# Generated by Django 2.2.16 on 2020-10-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_auto_20201019_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Django - Polling Subject'),
        ),
    ]
