# Generated by Django 2.2.16 on 2020-10-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0005_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Vote Option'),
        ),
    ]
